export const INCREASE_VOTE = "INCREASE_VOTE";  
export const DECREASE_VOTE  = "DECREASE_VOTE";



export const LOADING_CHALLENGES = "LOADING_CHALLENGES";  
export const SET_CHALLENGES  = "SET_CHALLENGES";


export const LOADING_SOLUTIONS = "LOADING_SOLUTIONS ";  
export const SET_SOLUTIONS = "SET_SOLUTIONS";


export const LOADING_SOLUTION = "LOADING_SOLUTION ";  
export const SET_SOLUTION= "SET_SOLUTION";


export const SET_USER = "SET_USER"
export const LOADING_USER = "LOADING_USER"


export const CURRENT_USER = "CURRENT_USER"









