export const LOADING_SOLUTION = "LOADING_SOLUTION ";  
export const SET_SOLUTION= "SET_SOLUTION";


export const LOADING_USER = "LOADING_USER"
export const SET_USER = "SET_USER"
export const LOADING_USERS = "LOADING_USERS"
export const SET_USERS = "SET_USERS"
export const CURRENT_USER = "CURRENT_USER"
export const  REMOVE_CURRENT_SESSION = "REMOVE_CURRENT_SESSION"



export const LOADING_CHALLENGES = "LOADING_CHALLENGES";  
export const SET_CHALLENGES  = "SET_CHALLENGES";


export const ADDING_CHALLENGE = "ADDING_CHALLENGE" 
export const SET_CHALLENGE = "SET_CHALLENGE" 

export const LOADING_SOLUTIONS = "LOADING_SOLUTIONS";  
export const SET_SOLUTIONS = "SET_SOLUTIONS";


export const  CURRENT_CHALLENGE = "CURRENT_CHALLENGE"














